default_language_version:
  python: "3.12"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
        exclude: README.MD
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.13.3"
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/biomejs/pre-commit
    rev: "v2.2.5"
    hooks:
      - id: biome-format
        additional_dependencies: ["@biomejs/biome@2.1.1"]
        types_or: [javascript, ts]

  - repo: https://github.com/rstcheck/rstcheck
    rev: "v6.2.5"
    hooks:
      - id: rstcheck
        exclude: (tests/|sphinx_js/templates)
        additional_dependencies: ["rstcheck[sphinx,toml]"]

  - repo: https://github.com/codespell-project/codespell
    rev: "v2.4.1"
    hooks:
      - id: codespell

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.18.2"
    hooks:
      - id: mypy
        exclude: (tests/)
        args: []
        additional_dependencies:
          - attrs
          - cattrs
          - jinja2
          - nox
          - pydantic
          - pytest
          - sphinx
          - types-docutils
          - types-parsimonious
          - types-setuptools

ci:
  autoupdate_schedule: "quarterly"
